services:
  db:
    image: mariadb:lts
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    
  web:
    image: php:7.4-apache
    container_name: apache
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./conf/web/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

volumes:
  db_data:

