services:
  db:
    image: mariadb:lts
    container_name: mariadb
    restart: always
    environment:
      MUSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: dockerfile/apache/Dockerfile
    container_name: apache
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
      - phpmyadmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ABSOLUTE_URI: http://localhost/phpmyadmin
volumes:
  db_data:
